http:
  host: "0.0.0.0"
  port: "8090"

services:
  user_service: "http://users:8082"
  music_service: "http://users:8082/api/v1/musics"
  notification_service: "http://notifications:8080"
  payment_service: "http://payment_service:8080/api/v1/payments"
  session_service: "http://sessions:8081"