http:
  host: "0.0.0.0"
  port: "8090"

services:
  user_service: "http://127.0.0.1:8082"
  music_service: "http://127.0.0.1:8082/api/v1/musics"
  notification_service: "http://127.0.0.1:8080"
  payment_service: "payment_service:8080/api/v1/payments"
  session_service: "http://127.0.0.1:8081"